### ISSUE TITLE
distinct_at has been deprecated by Tidyverse

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/surimi#21]
https://dplyr.tidyverse.org/reference/distinct_all.html

consider using across() or pick() instead at: https://github.com/ocean-tracking-network/surimi/blob/main/R/otn_imos_column_map.R#L419

**Comment by jackVanish** [comment]
Don't know why this ticket wasn't shut down, I checked it out and it looks like we fixed that pretty much as soon as you opened it. So I'm gonna close it now!
